### ISSUE TITLE
Blacklisted users shouldn't be able to make purchases

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#101]
The purchase endpoint should check if the user is blacklisted

**Comment by rossloika** [comment]
I agree

**Comment by DJHARDY2K21** [comment]
I will work with this shortly!

**Comment by MidSpike** [comment]
> I will work with this shortly!

@DJHARDY2K21 any updates?

**Comment by DJHARDY2K21** [comment]
> @DJHARDY2K21 any updates?

I will work on it now.
