### ISSUE TITLE
User Notes Command

### ISSUE THREAD

**Issue by rossloika** [Inertia-Lighting/discord-bot-api-server#118]
I would like to see a command that could do the following;
```
!notes create <user> <content>
!notes update <note_id> <content>
!notes remove <note_id>
!notes purge <user>
!notes for <user>
!notes lookup <note_id>
```
This allows staff to create notes for users in situations like support tickets product swaps / transfers.

# Conditions
- staff only
- new database collection `user-notes`
- preferably able to upgrade to slash commands later

**Comment by rossloika** [comment]
@MidSpike @dr4wn Could I please have your input on this as-well

**Comment by MidSpike** [comment]
@WillFJS you have been assigned to this

**Comment by WillFJS** [comment]
I say we use slash command right out of the bat, maybe do a re-write of the bot to include slash commands

**Comment by MidSpike** [comment]
> I say we use slash command right out of the bat, maybe do a re-write of the bot to include slash commands

ignore the slash commands part for now, slash commands can wait, our staff would like to see this command

**Comment by rossloika** [comment]
@WillFJS I would like to see some progress on this command. The sooner it is released, the better.
