### ISSUE TITLE
Create an endpoint for `v1/auth/tokens/test`

### ISSUE THREAD

**Issue by TotoTheEgg** [Inertia-Lighting/discord-bot-api-server#125]
It would be very useful for 3rd-party (and our) software to be able to test the identity token inside of a game to see if it valid.

**Comment by MidSpike** [comment]
@rossloika @dr4wn I would like your opinions on this, I think it is a good idea as it will assist toto with his project.

**Comment by WillFJS** [comment]
@MidSpike what is @TotoTheEgg 's project?
I do agree that this is a good idea tho

**Comment by MidSpike** [comment]
> @MidSpike what is @TotoTheEgg 's project?

I'll let you know in Discord as it is not public yet

**Comment by rossloika** [comment]
👍 okay from me

**Comment by dr4wn** [comment]
okay from me
