### ISSUE TITLE
Support menu should use dropdowns

### ISSUE THREAD

**Issue by WillFJS** [Inertia-Lighting/discord-bot-api-server#127]
~~In the #support channel, we should change the embed to have a button that then DMS them and asks what support category they want, that way we can always just direct people to #support~~

> Instead, let's change the number selection screen to use a dropdown menu

**Comment by MidSpike** [comment]
@WillFJS not like that.

Instead, let's change the number selection screen to use a dropdown menu

**Comment by WillFJS** [comment]
is it possible to use dropdowns in locked channels?

**Comment by WillFJS** [comment]
smart
