### ISSUE TITLE
Postmortem of user-facing support ticket experience

### ISSUE THREAD

**Issue by TotoTheEgg** [Inertia-Lighting/discord-bot-api-server#135]
Once a ticket is closed, have bot DM user to rate their experience with inertia support, and see what we could do to better their support

**Comment by MidSpike** [comment]
@TotoTheEgg could you expand on the method of which we should ask the user?

**Comment by TotoTheEgg** [comment]
@MidSpike Yes, once a staff member closes the ticket the bot will DM them requesting them to use a dropdown or text button rating 1-5(or 10), and once they do a 1-5(10) rating it will tell them to respond with what we could do to better their experience in a message that will timeout after 10-50 minutes

**Comment by MidSpike** [comment]
@TotoTheEgg thank you for elaborating on your message, this sounds like a good idea.

@rossloika @dr4wn opinions?

**Comment by rossloika** [comment]
I love the idea, although I would like to see it work in a specific way, where once the ticket is closed, the bot sends the user a direct message with the ticket status as closed and, they also get a message within the direct message asking if they wish to give feedback of their experience with our support team in the ticket.

**Comment by TotoTheEgg** [comment]
> I love the idea, although I would like to see it work in a specific way, where once the ticket is closed, the bot sends the user a direct message with the ticket status as closed and, they also get a message within the direct message asking if they wish to give feedback of their experience with our support team in the ticket.

Would we also include a copy of the ticket transcript for users to be able to refer back to if they encounter an issue again so they dont need to open another ticket?

**Comment by rossloika** [comment]
> > I love the idea, although I would like to see it work in a specific way, where once the ticket is closed, the bot sends the user a direct message with the ticket status as closed and, they also get a message within the direct message asking if they wish to give feedback of their experience with our support team in the ticket.
> 
> Would we also include a copy of the ticket transcript for users to be able to refer back to if they encounter an issue again so they dont need to open another ticket?

Yes, we would also include a copy of the transcript.

**Comment by MidSpike** [comment]
> > I would not include transcripts until it looks nice and not a json file. Maybe look like ticket bots transcript
> 
> Could we use [this](https://github.com/MajorGamerJay/discordChatExporter) to export in a clean format?

The issue with this is that we can already do the vast majority of what this library aims to offer.  
The major difference being, we control the process currently.  
At best this library chucks messages into markdown format, which is something that I can easily do already.
