### ISSUE TITLE
Urgent: Discord Bot runs commands twice

### ISSUE THREAD

**Issue by dr4wn** [Inertia-Lighting/discord-bot-api-server#165]
<img width="712" alt="Screen Shot 2021-11-01 at 11 24 56 AM" src="https://user-images.githubusercontent.com/69976177/139696636-8393193a-f490-42ba-ad70-bdb88f02a3df.png">

Picture says enough, this assumes top priority

**Comment by TotoTheEgg** [comment]
@dr4wn Is there any chance of two bot instances running?

**Comment by TotoTheEgg** [comment]
After running a few commands I was unable to replicate the issue, looks like a second instance of the bot was launched.

**Comment by WillFJS** [comment]
Issue fixed, this can be closed
