### ISSUE TITLE
Remove reliance on bloxlink from our services

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#239]
![image](https://user-images.githubusercontent.com/22574513/161456449-ae39d868-213a-49f3-a901-15974e46f80d.png)

![image](https://user-images.githubusercontent.com/22574513/161456411-4e26e156-0e74-4e86-9f51-e9e72616cba3.png)

### The problem

We simply aren't going to pay bloxlink, so we will stop using it.

**Comment by MidSpike** [comment]
@rossloika while we're at it, should we remove the auto-verify system?

**Comment by rossloika** [comment]
Yes, yes and yes.
