### ISSUE TITLE
Manage Products and Karma

### ISSUE THREAD

**Issue by WillFJS** [Inertia-Lighting/discord-bot-api-server#263]
The manage products and the manage karma command should accept a command option called "reason", and the commands should also log that reason to a logging area

**Comment by MidSpike** [comment]
I like this idea, @rossloika what do you think?

**Comment by rossloika** [comment]
It's a good idea, but who's gonna be the one to execute it, you or will?

**Comment by MidSpike** [comment]
@rossloika anyone is welcome to contribute by submitting a PR
