### ISSUE TITLE
Change all messages sent by the bot to be message embeds

### ISSUE THREAD

**Issue by DJHARDY2K21** [Inertia-Lighting/discord-bot-api-server#52]
Assign message embeds for all the commands!

This will help the bot look neater and not all over the place with 75% embeds, and 25% standard text!

**Comment by MidSpike** [comment]
@DJHARDY2K21 This sounds like a useful contribution, feel free to open a pull request and make the changes yourself.
I have @Will3126 oversee the pull request and this issue.

**Comment by itsdrawn** [comment]
This issue will be closed in a few hours if a pull request is not assigned or created in relation to this topic.

**Comment by MidSpike** [comment]
> This issue will be closed in a few hours if a pull request is not assigned or created in relation to this topic.

I agree, this issue has been open for a while without any progress having been made to it.

**Comment by MidSpike** [comment]
closing for lack of response
