### ISSUE TITLE
Integrate PayPal backend-api for upcoming website changes

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#54]
@itsdrawn @rossloika should @Will3126 and I start work on implementing the back-end logic for paypal purchases being conducted via our website?
Keep in mind that any code produced from this should be heavily scrutinized and tested before usage in production.

**Comment by rossloika** [comment]
Sounds good to be, having an early start on the back-end logic for Paypal will assist us in getting PayPal sales within the website out and running once completed and tested.

**Comment by Will3126** [comment]
Yes I do agree that we should start on it, will need heavy testing and make sure their is no flaws

**Comment by MidSpike** [comment]
Ok, this project is going to take a lot longer than I initially thought...
The PayPal documentation is absolute shit...
Everytime I think I found what I need, it just leads me somewhere completely unrelated or deprecated.
`¯\_(ツ)_/¯`

**Comment by MidSpike** [comment]
Update: we are going to use Braintree which is a subsidiary of PayPal b/c it has far superior docs, *go figure*.

**Comment by MidSpike** [comment]
Along with these changes, the server-side paypal integrations will not be contained in this project and shall be moved to a brand new api server dedicated for the website

**Comment by MidSpike** [comment]
Closing issue to re-open in website repo
