### ISSUE TITLE
Use the Discord "reply" feature for users to trace back what message went for which command.

### ISSUE THREAD

**Issue by itsdrawn** [Inertia-Lighting/discord-bot-api-server#56]
Just wondering, is this possible? I've seen this feature with different bots across Discord & I think this could be a quality of life improvement.

**Comment by MidSpike** [comment]
As of this moment in time, this is not (easily) possible for us.

We are waiting on Discord.js (the library that we use) to update to a newer version of the Discord Gateway.

**Comment by itsdrawn** [comment]
> As of this moment in time, this is not (easily) possible for us.
> 
> We are waiting on Discord.js (the library that we use) to update to a newer version of the Discord Gateway.

Understood. Closing this issue now.
