### ISSUE TITLE
"Users" role is given before membership verification gate has finished

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#60]
The "Users" role should not be given until the user has passed the membership verification gate.

**Comment by MidSpike** [comment]
I looked into this issue and we will have to wait for `Discord.js` to update to `v13`.
This will remain open until fixed.

**Comment by WillFJS** [comment]
This issue can be moved into #71

**Comment by MidSpike** [comment]
> This issue can be moved into #71

incorrect, this shall remain separate

**Comment by MidSpike** [comment]
@WillFJS can you investigate this further as it may no longer be relevant

**Comment by DJHARDY2K21** [comment]
> @WillFJS can you investigate this further as it may no longer be relevant

Once you have merged into V13, I can work on this bug.

**Comment by DJHARDY2K21** [comment]
Has this been worked on? Or am I needed to work on it

**Comment by MidSpike** [comment]
> Has this been worked on? Or am I needed to work on it

This still needs to be investigated.

Discord claims that if a user is given a role it will cause them to bypass the member welcome screen.

We need to determine if this is true as our bot automatically gives the "User" role when a member joins.

**Comment by DJHARDY2K21** [comment]
it is true, It allows them to pass the gate.

**Comment by WillFJS** [comment]
Gonna work on this today

**Comment by MidSpike** [comment]
> Gonna work on this today

@WillFJS any updates on this?
