### ISSUE TITLE
!products command should include images for each product

### ISSUE THREAD

**Issue by DJHARDY2K21** [Inertia-Lighting/discord-bot-api-server#67]
Products command should include a picture of the product, This helps with people see an image of the product before purchasing.
It will also help keep commands smaller, and can be easily updated!

**Comment by MidSpike** [comment]
@DJHARDY2K21 I agree with this suggestion...
Let's see what the others think.

**Comment by rossloika** [comment]
I agree with this as it will assist our customers in seeing how our products look before choosing to go into the product hub or even choosing to purchase a product.

**Comment by DJHARDY2K21** [comment]
Update: Having a gif within the embed showing the panel / product (Transition from to another)

**Comment by MidSpike** [comment]
# Update
## Goals
- the `image` will be used in the embed to showcase the **panel**
- the `thumbnail` will be used in the embed to showcase the **product** itself

**Comment by WillFJS** [comment]
We have product testing games coming soon, I think it would be better to just have the testing games.

**Comment by DJHARDY2K21** [comment]
Would also be nice to have them within the bot too, this will help with quick / easy access.

**Comment by MidSpike** [comment]
> Would also be nice to have them within the bot too, this will help with quick / easy access.

Preferably we will be storing them in our website

**Comment by DJHARDY2K21** [comment]
> > Would also be nice to have them within the bot too, this will help with quick / easy access.
> 
> Preferably we will be storing them in our website

Okay, What about setting the thumbnail on the products command the images.

**Comment by MidSpike** [comment]
@WillFJS bumping you on this to see if our staff have created the product images yet

**Comment by WillFJS** [comment]
staff has been too busy to create images, soon

**Comment by WillFJS** [comment]
product images have been created by @rossloika they are on the website to be seen by everyone.

**Comment by MidSpike** [comment]
the command now includes images, this can close
