### ISSUE TITLE
Suggestion: product channels should use MessageComponent buttons for the product download

### ISSUE THREAD

**Issue by DJHARDY2K21** [Inertia-Lighting/discord-bot-api-server#68]
In my opinion i think that all download channels should have an embed within the channel with an interaction button that leads them to download the product file, This will also make the channels look alot more cleaner!

**Comment by MidSpike** [comment]
This is a good suggestion for when we upgrade to DJSv13 when it comes out

**Comment by DJHARDY2K21** [comment]
I would happily work along getting the v13 working within the bot if needed, also can do the api interactions.

Maybe also introduce slash commands 👍

**Comment by MidSpike** [comment]
@rossloika @itsdrawn what are your opinions on this?

**Comment by WillFJS** [comment]
Should be done with #71

**Comment by MidSpike** [comment]
> Should be done with #71

incorrect, Keep separate

**Comment by MidSpike** [comment]
This suggestion is no longer applicable.
Product download channels will cease to exist soon.
