### ISSUE TITLE
Due to an issue I witnessed earlier, 

### ISSUE THREAD

**Issue by DJHARDY2K21** [Inertia-Lighting/discord-bot-api-server#70]
Due to an issue in a paypal ticket, They thought there was a purchase of $1.50, they was then told it was $2, 

In terms of this, The tax should be added on in the embed for example $1.50 + ($0.50 tax)

**Comment by MidSpike** [comment]
@itsdrawn care to follow up your closing with a reason

**Comment by itsdrawn** [comment]
fees vary & have to be calculated inside the ticket
