### ISSUE TITLE
Blacklist command should be more specific with errors

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#85]
![Screenshot_20210624-051759](https://user-images.githubusercontent.com/22574513/123237437-ad7bcd00-d4ab-11eb-8c94-27ad7b80fbe1.jpg)

This should have said "please specify a valid user"

**Comment by DJHARDY2K21** [comment]
Would you like me to work with this enhancement.

**Comment by MidSpike** [comment]
> Would you like me to work with this enhancement.

go for it

**Comment by MidSpike** [comment]
@MidSpike @DJHARDY2K21 can you work on this?

**Comment by MidSpike** [comment]
@WillFJS  @DJHARDY2K21 can you work on this?

**Comment by WillFJS** [comment]
go for it @DJHARDY2K21

**Comment by DJHARDY2K21** [comment]
This issue can now be closed.
