### ISSUE TITLE
Products purchase endpoint should use product codes instead of a product_id

### ISSUE THREAD

**Issue by MidSpike** [Inertia-Lighting/discord-bot-api-server#95]
# Currently
We are only accepting a singular `roblox_product_id` in the `user/products/purchase` endpoint.

# Problem
This is not very ideal for us, as `roblox_product_id` is not a unique identifier for us, and is reliant on Roblox.  
Additionally, by only allowing a singular product_id per purchase, this prevents us from easily expanding our paypal system to support multiple products per purchase.  

# Proposal
Firstly, these modifications will exist on v2 of the `user/products/purchase` endpoint.
I propose that we remove `roblox_product_id` from the purchase endpoint, and instead use an array of product codes.  
Before:
```json5
{
    /* ... */
    "roblox_product_id": /* string */,
}
```
After:
```json5
{
    /* ... */
    "product_codes": [
        /* string */,
        /* ... */
    ],
}
```
A minimum of one product code must be provided.  
Additionally, if any of the provided product codes are invalid, the request should fail.

# Feedback
@rossloika @itsdrawn what are your thoughts on this?

**Comment by DJHARDY2K21** [comment]
Yes, in my opinion Product codes should be used within the code + other stuff to keep everything as one thing and not code / id this will stop the code from looking horrid

**Comment by rossloika** [comment]
I agree with this, as it will assist in overall better functionality.
